_BASE_: 'diffusion.yaml'

###################################### DATALOADER ######################################
DATALOADER:
  INFERENCE_TRAIN: True

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_weights}'

####################################### decode strategy ####################################### 
DECODE_STRATEGY:
  NAME: 'DiffusionSampler'
  DIFFUSION:
    TIMESTEPS: 50
    TIME_DIFFERENCE: 0.0
    SAMPLE_NOISE: False
