_BASE_: 'diffusion_rl.yaml'

###################################### DATALOADER ######################################
DATALOADER:
  INFERENCE_TRAIN: True

######################################### Engine #########################################
ENGINE:
  NAME: 'BitDiffusionTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_weights}'

####################################### decode strategy ####################################### 
DECODE_STRATEGY:
  NAME: 'DiffusionSampler'
  DIFFUSION:
    TIMESTEPS: 20
    TIME_DIFFERENCE: 0.0
    SAMPLE_NOISE: False
